# Multi-package project Makefile script.
.POSIX:
help:

#MAKE = make # (GNU make variants: make (Linux) gmake (FreeBSD)

parent = <%=parent%>
version = <%=version%>
SUBDIRS = common app

.PHONY: help clean clobber compile spec
help: $(SUBDIRS)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
	@echo "##### Top-level multiproject: $(parent) #####"
	@echo "Usage: $(MAKE) [SUBDIRS="$(SUBDIRS)"] [target]"
compile spec: $(SUBDIRS)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
clean: $(SUBDIRS)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
	-rm -fr core* *~ .*~ build/* *.log */*.log
clobber: $(SUBDIRS)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done

#----------------------------------------
FMTS ?= tar.gz,zip
distdir = $(parent)-$(version)

pkg/$(distdir) : 
	-@mkdir -p pkg/$(distdir) ; cp -f exclude.lst pkg/
#	#-zip -9 -q --exclude @exclude.lst -r - . | unzip -od pkg/$(distdir) -
	-tar --format=posix --dereference --exclude-from=exclude.lst -cf - . | tar -xpf - -C pkg/$(distdir)

.PHONY: gem uninstall install dist package rubocop yard
dist package | pkg/$(distdir): $(SUBDIRS)
	-@for fmt in `echo $(FMTS) | tr ',' ' '` ; do \
		case $$fmt in \
			7z) echo "### pkg/$(distdir).7z ###" ; \
				rm -f pkg/$(distdir).7z ; \
				(cd pkg ; 7za a -t7z -mx=9 $(distdir).7z $(distdir)) ;; \
			zip) echo "### pkg/$(distdir).zip ###" ; \
				rm -f pkg/$(distdir).zip ; \
				(cd pkg ; zip -9 -q -r $(distdir).zip $(distdir)) ;; \
			*) tarext=`echo $$fmt | grep -e '^tar$$' -e '^tar.xz$$' -e '^tar.zst$$' -e '^tar.bz2$$' || echo tar.gz` ; \
				echo "### pkg/$(distdir).$$tarext ###" ; \
				rm -f pkg/$(distdir).$$tarext ; \
				(cd pkg ; tar --posix -h -caf $(distdir).$$tarext $(distdir)) ;; \
		esac \
	done
	-@rm -r pkg/$(distdir)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
gem uninstall install rubocop yard: $(SUBDIRS)
	-for dirX in $^ ; do $(MAKE) -C $$dirX $@ ; done
