require 'introrb/scriptexplore/version'
require 'introrb/scriptexplore/lib'
require 'introrb/scriptexplore/person'
# require 'introrb/scriptexplore/classic'
require 'introrb/scriptexplore/app'
require 'introrb/scriptexplore/cli'
